### ISSUE TITLE
Host on Habitica-Webhooks

### ISSUE THREAD

**Issue by paglias** [cvuorinen/habitica-github-bot#4]
Hi @cvuorinen , I'm sorry this took so long but we would like to enable this webhook to post about new issues in the Aspiring Blacksmiths guild, but we'd prefer to use an existing small app that already handled some webhooks (from github and other sources), [Habitica-Webhooks](https://github.com/HabitRPG/Habitica-Webhooks), instead of setting up something new on netlify since we don't currently use the service.

Do you mind if I take the code from here and incorporate it there? Of course you would be recognized as the original author (or if you want to post a PR yourself )

Thanks,
Matteo from Habitica

**Comment by cvuorinen** [comment]
No worries. It's totally fine by me if you take the code from here. It was built for that purpose. I can also make a PR if you are busy with other things.
